using System;
using System.Collections.Generic;
using System.IO;

namespace Tsukuru.Maps.Packer
{
	public class MapSpecificFileGenerator : IDisposable
	{
		private readonly Dictionary<string, string> _autoGeneratedFiles;
		private readonly List<string> _directoriesToScan;

	    public MapSpecificFileGenerator(List<string> directoriesToScan)
	    {
		    _directoriesToScan = directoriesToScan;
		    _autoGeneratedFiles = new Dictionary<string, string>();
	    }

	    public void Generate(string mapName)
	    {
		    foreach (string directory in _directoriesToScan)
		    {
			    var directoryInfo = new DirectoryInfo(directory);

			    var files = directoryInfo.GetFiles("*{Tsukuru.MapName}*", SearchOption.AllDirectories);

			    foreach (var file in files)
			    {
				    string oldFileName = file.FullName;
				    string newFileName = file.FullName.Replace("{Tsukuru.MapName}", mapName);

					file.MoveTo(newFileName);
					_autoGeneratedFiles.Add(newFileName, oldFileName);
			    }
		    }
	    }

		public void Dispose()
		{
			foreach (var pair in _autoGeneratedFiles)
			{
				var fileInfo = new FileInfo(pair.Key);

				if (!fileInfo.Exists)
				{
					continue;
				}

				fileInfo.MoveTo(pair.Value);
			}
		}
	}
}
